set nocompatible
filetype indent plugin on
syntax on
colorscheme monokai
set hidden
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set nostartofline
set autoindent
set nostartofline
set cc=80
set ruler
set laststatus=2
set confirm
set visualbell
set t_Co=256
set t_vb=
set mouse=a
set cmdheight=2
set number
set notimeout ttimeout ttimeoutlen=200
set shiftwidth=4
set softtabstop=4
set expandtab
